/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mphpayroll;

import com.opencsv.CSVReader;
import com.opencsv.exceptions.CsvValidationException;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author AXISMEG
 */
public class emplist extends javax.swing.JFrame {

    /**
     * Creates new form empreg
     */
    public emplist() {
        initComponents();
       
        
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_close = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_emptable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_close.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jb_close.setText("CLOSE");
        jb_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_closeActionPerformed(evt);
            }
        });
        getContentPane().add(jb_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 540, 120, 40));

        jt_emptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee No.", "Last Name", "First Name", "Birthday", "Phone Number", "SSS No.", "PhilHealth No.", "TIN No.", "PAGIBIG No.", "Status", "Position"
            }
        ));
        jScrollPane1.setViewportView(jt_emptable);
        if (jt_emptable.getColumnModel().getColumnCount() > 0) {
            jt_emptable.getColumnModel().getColumn(0).setHeaderValue("Employee No.");
            jt_emptable.getColumnModel().getColumn(1).setHeaderValue("Last Name");
            jt_emptable.getColumnModel().getColumn(2).setHeaderValue("First Name");
            jt_emptable.getColumnModel().getColumn(3).setHeaderValue("Birthday");
            jt_emptable.getColumnModel().getColumn(4).setHeaderValue("Phone Number");
            jt_emptable.getColumnModel().getColumn(5).setHeaderValue("SSS No.");
            jt_emptable.getColumnModel().getColumn(6).setHeaderValue("PhilHealth No.");
            jt_emptable.getColumnModel().getColumn(7).setHeaderValue("TIN No.");
            jt_emptable.getColumnModel().getColumn(8).setHeaderValue("PAGIBIG No.");
            jt_emptable.getColumnModel().getColumn(9).setHeaderValue("Status");
            jt_emptable.getColumnModel().getColumn(10).setHeaderValue("Position");
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 850, 490));

        jLabel1.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+("\\src\\main\\java\\com\\mycompany\\mphpayroll\\Images\\bgmain.png")));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_closeActionPerformed

        empadmin nextForm = new empadmin();
        nextForm.setVisible(true);

        this.dispose();

    }//GEN-LAST:event_jb_closeActionPerformed

   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emplist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emplist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emplist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emplist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emplist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_close;
    private javax.swing.JTable jt_emptable;
    // End of variables declaration//GEN-END:variables
}

