/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LogIn;

import javax.swing.JOptionPane;
import EmployeeDetails.empdetails;

/**
 *
 * @author AXISMEG
 */
public class AdminLogIn extends javax.swing.JFrame {

    
    private static final String USERNAME = "admin";
    private static final String PASSWORD = "password";
    
    /**
     * Creates new form AdminLogIn
     */
    public AdminLogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        loginbutt = new javax.swing.JButton();
        usertf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        passtf = new javax.swing.JPasswordField();
        canbutt1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Payroll APP");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MotorPH");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("ADMIN LOGIN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USERNAME :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 217, -1, -1));

        loginbutt.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        loginbutt.setText("Log In");
        loginbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttActionPerformed(evt);
            }
        });
        getContentPane().add(loginbutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        usertf.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        getContentPane().add(usertf, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 214, 98, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PASSWORD :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 251, -1, -1));

        passtf.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        passtf.setToolTipText("");
        getContentPane().add(passtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 248, 98, -1));

        canbutt1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        canbutt1.setText("Cancel");
        canbutt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canbutt1ActionPerformed(evt);
            }
        });
        getContentPane().add(canbutt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\LogIn\\login.jpg"));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttActionPerformed
        // TODO add your handling code here:
        
        String user = usertf.getText();
        String pass = passtf.getText();
        
        if (user.equals(USERNAME) && pass.equals(PASSWORD)){
            
            JOptionPane.showMessageDialog(this, "Login Succesful");
            
            this.dispose();
                                   
            empdetails nextForm1 = new empdetails();
            nextForm1.setVisible(true);
            
        } else {
            JOptionPane.showMessageDialog(this,"Invalid Username or Password!!!");
        }
        
    }//GEN-LAST:event_loginbuttActionPerformed

    private void canbutt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canbutt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_canbutt1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canbutt1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton loginbutt;
    private javax.swing.JPasswordField passtf;
    private javax.swing.JTextField usertf;
    // End of variables declaration//GEN-END:variables
}
