/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LogIn;

import javax.swing.JOptionPane;
import EmployeeDetails.empdetails;

/**
 *
 * @author AXISMEG
 */
public class EmployeeLogIn extends javax.swing.JFrame {

    private static final String USERNAME = "employee";
    private static final String PASSWORD = "password";
    
    /**
     * Creates new form EmployeeLogIn
     */
    public EmployeeLogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        eusertf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        epasstf = new javax.swing.JPasswordField();
        eloginbutt = new javax.swing.JButton();
        ecanbutt = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MotorPH");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Payroll APP");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("EMPLOYEE LOGIN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USERNAME :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 217, -1, -1));

        eusertf.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        getContentPane().add(eusertf, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 214, 98, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PASSWORD :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 251, -1, -1));

        epasstf.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        epasstf.setToolTipText("");
        getContentPane().add(epasstf, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 248, 98, -1));

        eloginbutt.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        eloginbutt.setText("Log In");
        eloginbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eloginbuttActionPerformed(evt);
            }
        });
        getContentPane().add(eloginbutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        ecanbutt.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        ecanbutt.setText("Cancel");
        ecanbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecanbuttActionPerformed(evt);
            }
        });
        getContentPane().add(ecanbutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\LogIn\\login.jpg"));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eloginbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eloginbuttActionPerformed
        // TODO add your handling code here:

        String user = eusertf.getText();
        String pass = epasstf.getText();

        if (user.equals(USERNAME) && pass.equals(PASSWORD)){

            JOptionPane.showMessageDialog(this, "Login Succesful");

            this.dispose();

            empdetails nextForm1 = new empdetails();
            nextForm1.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(this,"Invalid Username or Password!!!");
        }

    }//GEN-LAST:event_eloginbuttActionPerformed

    private void ecanbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecanbuttActionPerformed
        // TODO add your handling code here:

        AdminEmployee nextForm2 = new AdminEmployee();
        nextForm2.setVisible(true);
    }//GEN-LAST:event_ecanbuttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeLogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ecanbutt;
    private javax.swing.JButton eloginbutt;
    private javax.swing.JPasswordField epasstf;
    private javax.swing.JTextField eusertf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
